export const produtos = [
  {
    id: 1,
    nome: 'RTX3060',
    preco: '3600,00',
    descricao:
      'Excelente placa focada nas jogatinas em 1080P.',
    imagePath:
      'https://m.media-amazon.com/images/I/81ZKtpbPhHS._AC_SY450_.jpg',
  },
  {
    id: 2,
    nome: 'RTX3060TI',
    preco: '4000,00',
    descricao: 'Tipo a RTX3060, só que mais cara, com 3% de eficiencia a mais, e as vezes mais bonita',
    imagePath: 'https://http2.mlstatic.com/D_NQ_NP_968105-MLA48381643794_112021-W.jpg',
  },
  {
    id: 3,
    nome: 'Cavalinho do gugu',
    preco: '999.999.999,00',
    descricao: 'Meio de transporte mais veloz de toda a humanidade, possibilita que o úsuario se locomova a incriveis 3 saltos por segundo.',
    imagePath: 'https://superlegalbrinquedos.vteximg.com.br/arquivos/ids/170118-800-800/500_Cavalinho_Upa_Upa_do_GuGu_Azul_Lider_1.jpg?v=637096999996670000',
  },
  {
    id: 4,
    nome: 'Gato de trança',
    preco: '40,00',
    descricao: 'Gato nórdico com habilidades misticas, diz a lenda que ele é capaz de encontrar a pedra filosofal. PS:Aligmentar com ração sem corante.',
    imagePath: 'https://www.oversodoinverso.com.br/wp-content/uploads/2019/12/Alguem-photoshops-animais-em-coisas-aleatorias-e-a-Internet-adora-40-fotos-OT7UAyYtQ8.jpg',
  },
  {
    id: 5,
    nome: 'Banana pato',
    preco: '00,01',
    descricao: 'Eu não sei porque alguém compraria isso, mas está ae, é uma banana com cabeça de pato..Boa noite.',
    imagePath: 'http://tendencee.com.br/wp-content/uploads/2019/12/Alguem-photoshops-animais-em-coisas-aleatorias-e-a-Internet-adora-40-fotos-fPipSnA39F.jpg',
  },
  {
    id: 6,
    nome: 'Telefone do Garfield',
    preco: '200,00',
    descricao: 'Lindo telefone, exclusivo para as pessoas que odeiam segunda-feira.',
    imagePath: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTuGGMRwglM3kzj82YtzNDjLACjfLP7Tbk6KA&usqp=CAU',
  },
  {
    id: 7,
    nome: 'Pato maligno Cauã',
    preco: '2,00',
    descricao: 'Companheiro, simpatico, carinhoso, amigo, esse pato não possui nenhuma destas qualidades.',
    imagePath: 'https://img.wattpad.com/cover/244742785-352-k3301.jpg',
  },
  {
    id: 8,
    nome: 'Gato banana triste',
    preco: '10,00',
    descricao: 'Será você quem vai fazer o pato banana feliz? Provavelmente não...',
    imagePath: 'https://avowhcbwko.cloudimg.io/v7/https://empreender.nyc3.cdn.digitaloceanspaces.com/grupowhats/3be7dff8942a25edf189c9326f7de3f0?w=400&org_if_sml=1',
  },
  {
    id: 9,
    nome: 'Doguinho na hora de almoço',
    preco: '40,00',
    descricao: 'Esse produto é apenas uma NFT do doguinho, o real está trabalhando, não o incomode.',
    imagePath: 'https://i.pinimg.com/564x/e3/81/f9/e381f94e800c75721a67f1300db80de3.jpg',
  },
  {
    id: 10,
    nome: 'Doguinho Guerry',
    preco: '9,00',
    descricao: 'Não sei, existe algo no olhar desse cachorro que te chama, cuidado para não fazer o cartão da loja.',
    imagePath: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRQoRoSCWGGIhgMqaaZmTGvlgsY2gnmsKtl28xsIyB-m054iS85QgKNTepc6UXshfMgKWs&usqp=CAU',
  },
  {
    id: 11,
    nome: 'Bross 160 dog edition',
    preco: '14.000,00',
    descricao: 'É uma boa moto, roda bem no asfalto, usa aditivada, consumo médio de 1km/petisco.',
    imagePath: 'https://img.ifunny.co/images/0d5896f14040d1073f5058c196b64678b31e3aff672ee128031ce1e9919280fa_1.jpg',
  },
  {
    id: 12,
    nome: 'Pikachu paulista',
    preco: '10,00',
    descricao: 'Ele coloca katchup na pizza, cuidado.',
    imagePath: 'https://img.wattpad.com/cover/173624654-352-k333894.jpg',
  },
  {
    id: 13,
    nome: 'Girrassois',
    preco: '14,00',
    descricao: 'Alguma coisa mais normal pra lembrar vocês que ainda somos uma loja.',
    imagePath: 'https://i.webfic.app/fic/b/Az-oKA0b2zwNzSXuJeO0Lg.jpg?fbwvna8mt',
  },
  {
    id: 14,
    nome: 'Gato de cueca',
    preco: '9,00',
    descricao: 'Não existe nada de parcial aqui, realmente é um gato de cueca, boa noite.',
    imagePath: 'https://pbs.twimg.com/media/Epy6Tq0XEAE9Q-X.jpg',
  },
];
